### ISSUE TITLE
Spiff expression in "or logic" ("||") is not working correctly in v1.7.0-beta-4

### ISSUE THREAD

**Issue by DimitarVoynov** [mandelsoft/spiff#18]
Hi @mandelsoft, 

we identified that due to the following change: https://github.com/mandelsoft/spiff/commit/f5332183feaf4bbdaa85934b0397bcb6caf737a4 spiff is not working correctly with the following set of yaml files: 

```
1) context-template.yml

...
terraform:
  db:
    name: (( merge || ( terraform.properties.inst_name "db" ) ))
    user: (( merge ))
    password: (( merge ))

  databases:
    - name: (( terraform.db.name ))
      user: (( terraform.db.user ))
      password: (( terraform.db.password ))
    - <<<: (( merge || ~ ))

  properties:
    <<<: (( merge ))
    inst_name: (( merge ))
.....
```
2) config.yml

```
---

credentials: (( merge ))

terraform:
  properties:
    inst_name: apps

  db:
    user: (( credentials.rds.appsdb.user ))
    password: ((!appsdb_password))

  databases:
    - name: availability
      password: ((!availability_password))
      user: availability_admin
    - name: xsuaa
      password: ((!xsuaa_password))
      user: xsuaa_admin

```
3) credentials.yml

```
---
credentials:
  rds:
    appsdb:
      user: admin
```
With spiff versions before v1.7.0-beta-4 the line: 

> name: (( merge || ( terraform.properties.inst_name "db" ) ))

correctly works - i.e. the value after "||" gets resolved to value "appsdb" - thus resulting in a correct merged context.yml file: 

```
terraform:
  databases:
    - name: availability
      password: ((!availability_password))
      user: availability_admin
    - name: xsuaa
      password: ((!xsuaa_password))
      user: xsuaa_admin
    - name: appsdb
      password: ((!appsdb_password))
      user: admin
```

while starting with version v1.7.0-beta-4 of spiff - the merged yml is wrong:

```
terraform:
  databases:
    - name: availability
      password: ((!availability_password))
      user: availability_admin
    - name: xsuaa
      password: ((!xsuaa_password))
      user: xsuaa_admin
    - name: xsuaa
      password: ((!xsuaa_password))
      user: xsuaa_admin
```

To us this looks like a bug or at least - a change that is not backward compatible. Can you please have a look/fix it? 

Thanks, 
Dimitar
